CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.benefit_guides (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content TEXT NOT NULL,
    embedding vector(768),
    source TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_benefit_guides_source
    ON public.benefit_guides(source);

CREATE INDEX IF NOT EXISTS idx_benefit_guides_embedding
    ON public.benefit_guides
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

CREATE OR REPLACE FUNCTION public.match_benefits(
    query_embedding vector(768),
    match_threshold FLOAT DEFAULT 0.1,
    match_count INT DEFAULT 4
)
RETURNS TABLE (
    id UUID,
    content TEXT,
    source TEXT,
    similarity FLOAT
)
LANGUAGE SQL
STABLE
AS $$
    SELECT
        benefit_guides.id,
        benefit_guides.content,
        benefit_guides.source,
        1 - (benefit_guides.embedding <=> query_embedding) AS similarity
    FROM public.benefit_guides
    WHERE benefit_guides.embedding IS NOT NULL
      AND 1 - (benefit_guides.embedding <=> query_embedding) >= match_threshold
    ORDER BY benefit_guides.embedding <=> query_embedding
    LIMIT match_count;
$$;

CREATE TABLE IF NOT EXISTS public.health_facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_of_health_facility TEXT NOT NULL,
    street TEXT,
    municipality_city TEXT,
    region TEXT,
    is_philhealth BOOLEAN NOT NULL DEFAULT FALSE,
    is_malasakit BOOLEAN NOT NULL DEFAULT FALSE,
    expire_date DATE,
    source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_health_facilities_city
    ON public.health_facilities(municipality_city);

CREATE INDEX IF NOT EXISTS idx_health_facilities_region
    ON public.health_facilities(region);

CREATE INDEX IF NOT EXISTS idx_health_facilities_benefit_flags
    ON public.health_facilities(is_philhealth, is_malasakit);

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_health_facilities_updated_at ON public.health_facilities;
CREATE TRIGGER trg_health_facilities_updated_at
BEFORE UPDATE ON public.health_facilities
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
